"""Create initial tables

Revision ID: 488cc286dc6b
Revises: 
Create Date: 2025-08-04 18:45:32.519019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488cc286dc6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('nome_produtor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtores_cpf_cnpj'), 'produtores', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_produtores_id'), 'produtores', ['id'], unique=False)
    op.create_table('propriedades_rurais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fazenda', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('area_total_ha', sa.Float(), nullable=False),
    sa.Column('area_agricultavel_ha', sa.Float(), nullable=False),
    sa.Column('area_vegetacao_ha', sa.Float(), nullable=False),
    sa.Column('produtor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propriedades_rurais_id'), 'propriedades_rurais', ['id'], unique=False)
    op.create_table('culturas_plantadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cultura', sa.String(), nullable=False),
    sa.Column('safra', sa.String(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedades_rurais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_culturas_plantadas_id'), 'culturas_plantadas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_culturas_plantadas_id'), table_name='culturas_plantadas')
    op.drop_table('culturas_plantadas')
    op.drop_index(op.f('ix_propriedades_rurais_id'), table_name='propriedades_rurais')
    op.drop_table('propriedades_rurais')
    op.drop_index(op.f('ix_produtores_id'), table_name='produtores')
    op.drop_index(op.f('ix_produtores_cpf_cnpj'), table_name='produtores')
    op.drop_table('produtores')
    # ### end Alembic commands ###
